# Generated by Django 5.2.7 on 2025-10-07 15:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat_estados_de_entregas',
            fields=[
                ('id_estado_de_entrega', models.AutoField(primary_key=True, serialize=False)),
                ('estado_de_entrega', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cat_estatus_de_vehiculos',
            fields=[
                ('id_estatus_de_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('estatus_de_vehiculo', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cat_tipos_de_entregas',
            fields=[
                ('id_tipo_de_entrega', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_de_entrega', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cat_tipos_de_licencias',
            fields=[
                ('id_tipo_de_licencia', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_de_licencia', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cat_tipos_de_vehiculos',
            fields=[
                ('id_tipo_de_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_de_vehiculo', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('telefono', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{10,13}$', message='Número de teléfono inválido')])),
            ],
        ),
        migrations.CreateModel(
            name='Repartidores',
            fields=[
                ('id_repartidor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('telefono', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{10,13}$', message='Número de teléfono inválido')])),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.TextField()),
                ('numero_exterior', models.CharField(max_length=20)),
                ('numero_interior', models.CharField(blank=True, max_length=20, null=True)),
                ('colonia', models.TextField()),
                ('delegacion', models.TextField()),
                ('cp', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$', message='Código postal inválido')])),
                ('pais', models.CharField(default='México', max_length=7)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Licencias_de_repartidor',
            fields=[
                ('id_licencia_de_repartidor', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_de_licencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cat_tipos_de_licencias')),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.repartidores')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.TextField()),
                ('km_por_litro', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('estatus_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cat_estatus_de_vehiculos')),
                ('repartidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.repartidores')),
                ('tipo_de_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cat_tipos_de_vehiculos')),
            ],
        ),
        migrations.CreateModel(
            name='Entregas',
            fields=[
                ('id_entrega', models.AutoField(primary_key=True, serialize=False)),
                ('beneficios', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.clientes')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.direcciones')),
                ('estado_de_la_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cat_estados_de_entregas')),
                ('tipo_de_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cat_tipos_de_entregas')),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.repartidores')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vehiculos')),
            ],
        ),
    ]
