# Generated by Django 5.2.7 on 2025-10-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregas',
            name='estado_de_la_entrega',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('terminada', 'Terminada'), ('reagendada', 'Reagendada')], default='reagendada', max_length=15),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='estatus_vehiculo',
            field=models.CharField(choices=[('libre', 'Libre'), ('ocupado', 'Ocupado')], default='libre', max_length=10),
        ),
        migrations.AlterField(
            model_name='entregas',
            name='tipo_de_entrega',
            field=models.CharField(choices=[('campo', 'Campo'), ('masivo', 'Masivo')], default='campo', max_length=10),
        ),
        migrations.AlterField(
            model_name='licencias_de_repartidor',
            name='tipo_de_licencia',
            field=models.CharField(choices=[('licencia_moto', 'Licencia para moto'), ('licencia_carro', 'Licencia para carro')], default='licencia_carro', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='tipo_de_vehiculo',
            field=models.CharField(choices=[('moto', 'Carro'), ('carro', 'Moto')], default='carro', max_length=10),
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='id_cliente',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='direcciones',
            old_name='id_direccion',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='direcciones',
            old_name='cliente',
            new_name='id_cliente',
        ),
        migrations.RenameField(
            model_name='entregas',
            old_name='id_entrega',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='entregas',
            old_name='cliente',
            new_name='id_cliente',
        ),
        migrations.RenameField(
            model_name='entregas',
            old_name='direccion',
            new_name='id_direccion',
        ),
        migrations.RenameField(
            model_name='entregas',
            old_name='repartidor',
            new_name='id_repartidor',
        ),
        migrations.RenameField(
            model_name='entregas',
            old_name='vehiculo',
            new_name='id_vehiculo',
        ),
        migrations.RenameField(
            model_name='licencias_de_repartidor',
            old_name='id_licencia_de_repartidor',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='licencias_de_repartidor',
            old_name='repartidor',
            new_name='id_repartidor',
        ),
        migrations.RenameField(
            model_name='repartidores',
            old_name='id_repartidor',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='vehiculos',
            old_name='id_vehiculo',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='vehiculos',
            old_name='repartidor',
            new_name='id_repartidor',
        ),
        migrations.AlterField(
            model_name='direcciones',
            name='pais',
            field=models.CharField(default='México', max_length=70),
        ),
        migrations.DeleteModel(
            name='Cat_estados_de_entregas',
        ),
        migrations.DeleteModel(
            name='Cat_estatus_de_vehiculos',
        ),
        migrations.DeleteModel(
            name='Cat_tipos_de_entregas',
        ),
        migrations.DeleteModel(
            name='Cat_tipos_de_licencias',
        ),
        migrations.DeleteModel(
            name='Cat_tipos_de_vehiculos',
        ),
    ]
