# Generated by Django 5.2.7 on 2025-10-07 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_entregas_estado_de_la_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregas',
            name='id_repartidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.repartidores'),
        ),
    ]
