# Generated by Django 5.2.7 on 2025-10-08 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_entregas_id_repartidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregas',
            name='id_vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.vehiculos'),
        ),
    ]
