# Generated by Django 5.2.6 on 2025-10-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatEstadosEntrega',
            fields=[
                ('id_estado_entrega', models.AutoField(db_comment='Identificador único del estado de entrega', primary_key=True, serialize=False)),
                ('nombre', models.TextField(db_comment='Nombre del estado de entrega (pendiente, entregada)', unique=True)),
            ],
            options={
                'db_table': 'cat_estados_entrega',
                'db_table_comment': 'Catálogo de estados de entrega',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatEstatusVehiculo',
            fields=[
                ('id_estatus_vehiculo', models.AutoField(db_comment='Identificador único del estatus', primary_key=True, serialize=False)),
                ('nombre', models.TextField(db_comment='Nombre del estatus (libre, ocupado)', unique=True)),
            ],
            options={
                'db_table': 'cat_estatus_vehiculo',
                'db_table_comment': 'Catálogo de estados de los vehículos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatTiposEntrega',
            fields=[
                ('id_tipo_entrega', models.AutoField(db_comment='Identificador único del tipo de entrega', primary_key=True, serialize=False)),
                ('nombre', models.TextField(db_comment='Nombre del tipo de entrega (campo, masivo)', unique=True)),
            ],
            options={
                'db_table': 'cat_tipos_entrega',
                'db_table_comment': 'Catálogo de tipos de entrega',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatTiposLicencia',
            fields=[
                ('id_tipo_licencia', models.AutoField(db_comment='Identificador único del tipo de licencia', primary_key=True, serialize=False)),
                ('nombre', models.TextField(db_comment='Nombre del tipo de licencia (moto, carro, etc.)', unique=True)),
            ],
            options={
                'db_table': 'cat_tipos_licencia',
                'db_table_comment': 'Catálogo de tipos de licencias de repartidor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatTiposVehiculo',
            fields=[
                ('id_tipo_vehiculo', models.AutoField(db_comment='Identificador único del tipo de vehículo', primary_key=True, serialize=False)),
                ('nombre', models.TextField(db_comment='Nombre del tipo de vehículo (moto, carro, etc.)', unique=True)),
            ],
            options={
                'db_table': 'cat_tipos_vehiculo',
                'db_table_comment': 'Catálogo de tipos de vehículos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(db_comment='Identificador único del cliente', primary_key=True, serialize=False)),
                ('nombre', models.TextField(db_comment='Nombre completo del cliente')),
                ('telefono', models.TextField(db_comment='Número de teléfono del cliente')),
            ],
            options={
                'db_table': 'clientes',
                'db_table_comment': 'Tabla de clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('id_direccion', models.AutoField(db_comment='Identificador único de la dirección', primary_key=True, serialize=False)),
                ('calle', models.TextField(db_comment='Nombre de la calle')),
                ('num_ext', models.TextField(db_comment='Número exterior')),
                ('num_int', models.TextField(blank=True, db_comment='Número interior (opcional)', null=True)),
                ('colonia', models.TextField(db_comment='Nombre de la colonia')),
                ('delegacion_municipio', models.TextField(db_comment='Delegación o municipio')),
                ('cp', models.TextField(db_comment='Código postal')),
                ('pais', models.TextField(db_comment='País, por defecto México')),
            ],
            options={
                'db_table': 'direcciones',
                'db_table_comment': 'Tabla de direcciones de clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entregas',
            fields=[
                ('id_entrega', models.AutoField(db_comment='Identificador único de la entrega', primary_key=True, serialize=False)),
                ('beneficios', models.TextField(blank=True, db_comment='Son los beneficios que se le entregaran al cliente', null=True)),
                ('monto_beneficio', models.DecimalField(blank=True, db_comment='Será el costo de los beneficios', decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'entregas',
                'db_table_comment': 'Tabla de entregas programadas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LicenciasRepartidor',
            fields=[
                ('id_licencia', models.AutoField(db_comment='Identificador único de la licencia', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'licencias_repartidor',
                'db_table_comment': 'Licencias que posee cada repartidor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Repartidores',
            fields=[
                ('id_repartidor', models.AutoField(db_comment='Identificador único del repartidor', primary_key=True, serialize=False)),
                ('nombre', models.TextField(db_comment='Nombre completo del repartidor')),
                ('telefono', models.TextField(db_comment='Número de teléfono del repartidor')),
                ('activo', models.BooleanField(blank=True, db_comment='Indica si el repartidor está activo', null=True)),
            ],
            options={
                'db_table': 'repartidores',
                'db_table_comment': 'Tabla de repartidores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id_vehiculo', models.AutoField(db_comment='Identificador único del vehículo', primary_key=True, serialize=False)),
                ('modelo', models.TextField(db_comment='Modelo del vehículo')),
                ('km_por_litro', models.DecimalField(db_comment='Rendimiento en kilómetros por litro', decimal_places=65535, max_digits=65535)),
            ],
            options={
                'db_table': 'vehiculos',
                'db_table_comment': 'Tabla de vehículos disponibles',
                'managed': False,
            },
        ),
    ]
