from .estatus_de_vehiculos import Estatus_de_vehiculos
from .estados_de_entregas import Estados_de_entregas
from .licencias_de_repartidor import Licencias_de_repartidor
from .tipos_de_licencias import Tipos_de_licencias
from .tipos_de_vehiculos import Tipos_de_vehiculos
from .tipos_de_entregas import Tipos_de_entregas
from .repartidores import Repartidores
from .direcciones import Direcciones
from .vehiculos import Vehiculos
from .clientes import Clientes
from .entregas import Entregas