from .cat_estatus_de_vehiculos import Cat_estatus_de_vehiculos
from .cat_estados_de_entregas import Cat_estados_de_entregas
from .licencias_de_repartidor import Licencias_de_repartidor
from .cat_tipos_de_licencias import Cat_tipos_de_licencias
from .cat_tipos_de_vehiculos import Cat_tipos_de_vehiculos
from .cat_tipos_de_entregas import Cat_tipos_de_entregas
from .repartidores import Repartidores
from .direcciones import Direcciones
from .vehiculos import Vehiculos
from .clientes import Clientes
from .entregas import Entregas